### ISSUE TITLE
How do I add GCI NES files?

### ISSUE THREAD

**Issue by 03bgood** [Cuyler36/ACNESCreator#2]
I can't find a tutorial online anywhere since this is new. How do I get the GCI files on to a GC memory card?

**Comment by Cuyler36** [comment]
You need to use GCMM (GameCube MemoryCard Manager).

You'll need a softmodded Wii or GameCube to be able to use that program. I found a guide here: https://www.youtube.com/watch?v=Gp2SydBCWGY

**Comment by 03bgood** [comment]
I do have a softmodded Wii, but I can't seem to add many NES games because I run out of space on the memory card. What do I do? The AC save is 57 blocks and the NES data is 1 block. That leaves only 1 block left from a memory card with 59 blocks. I do have a memory card with 251 blocks, should I use that?

**Comment by Cuyler36** [comment]
You can use that. Animal Crossing can detect the NES files even if they're on another memory card so long as it is in the other slot. So you can leave your 59 block memory card in Slot A and put your NES ROM save files on your 251 block memory card, then put that card in Slot B.

**Comment by 03bgood** [comment]
Oh, okay.

**Comment by Cuyler36** [comment]
If you still have problems, please contact me on Discord. My Discord tag is Cuyler#0602. I'm closing this now.
